FROM registry.access.redhat.com/rhel6.5

MAINTAINER sbylo@redhat.com

ENV TOMCAT_VERSION=7.0.70

# Set labels used in OpenShift to describe the builder image
LABEL io.k8s.description="Platform for serving web content" \
      io.k8s.display-name="Tomcat 7.0.70" \
      io.openshift.expose-services="8080:http" \
      io.openshift.tags="builder,html,tomcat"

# Install java
RUN cd /opt && yum -y install tar wget && wget -O - -q --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz" | tar xzf - && yum clean all -y

# Install Tomcat
Run cd /usr/local && curl -s http://www.us.apache.org/dist/tomcat/tomcat-7/v7.0.70/bin/apache-tomcat-7.0.70.tar.gz | tar xzf - && mv apache-tomcat-7.0.70 tomcat7

# Copy the S2I scripts to /usr/libexec/s2i
#COPY ./.s2i/bin/ /usr/libexec/s2i

# Defines the location of the S2I
LABEL io.openshift.s2i.scripts-url=image:///usr/local/s2i
# Copy the S2I scripts from ./.s2i/bin/ to /usr/local/s2i when making the builder image
COPY ./.s2i/bin/ /usr/local/s2i

RUN useradd -d /home/tomcat -m -u 1001 -g 0 tomcat && cd /usr/local/tomcat7 && chown -R tomcat:0 . 

WORKDIR /usr/local/tomcat7

ENV JAVA_HOME=/opt/jdk1.7.0_79 JRE_HOME=/opt/jdk1.7.0_79/jre 

EXPOSE 8080

USER 1001

#ENTRYPOINT ./bin/startup.sh && sleep 9999999999
# Set the default CMD to print the usage of the image, if somebody does docker run
CMD ["usage"]

